platform :ios, '7.0'
target 'ImitateLive'   do
 pod 'AFNetworking', '~> 3.1.0'
 pod 'SDWebImage', '~> 3.8.1'
 pod 'MJRefresh', '~> 3.1.9'
 pod 'HyphenateFullSDK', :git => 'https://github.com/easemob/hyphenate-full-cocoapods.git'
end
